# Generated by Django 3.0.7 on 2023-06-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20230613_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('MH', 'Maharashtra'),('HR', 'Hariyana')], max_length=100),
        ),
    ]
